server:
  port: 5300
spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
ftp_address: 192.168.1.139
ftp_port: 21
ftp_username: admin
ftp_password: admin
ftp_workdirectory: /home/admin
